import { HorizontalBox, VerticalBox, StandardTableView, GroupBox, StyleMetrics, LineEdit, Button } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "fast-down";
    HorizontalBox {
        vertical-stretch: 1;
        VerticalLayout {
            spacing: StyleMetrics.layout-spacing;
            HorizontalLayout {
                spacing: StyleMetrics.layout-spacing;
                Button {
                    text: @tr("Add");
                }

                Button {
                    text: @tr("Resume");
                }

                Button {
                    text: @tr("Stop");
                }

                Button {
                    text: @tr("Delete");
                }

                Button {
                    text: @tr("Settings");
                }
            }

            StandardTableView {
                columns: [
                    { title: @tr("File Name") },
                    { title: @tr("Size") },
                    { title: @tr("Status") },
                    { title: @tr("Bandwidth") },
                    { title: @tr("Remaining Time") },
                ];
                rows: [
                    [
                        { text: "Item 1" },
                        { text: "Item 2" },
                    ],
                    [
                        { text: "Item 1" },
                        { text: "Item 2" },
                    ],
                    [
                        { text: "Item 1" },
                        { text: "Item 2" },
                    ]
                ];
            }
        }
    }
}
