import { HorizontalBox, VerticalBox, TabWidget, StandardTableView, GroupBox, StyleMetrics, LineEdit, Button, ListView, TextEdit, ProgressIndicator } from "std-widgets.slint";
import { DownloadData, DownloadItem } from "download-item.slint";
import { Home } from "home.slint";


export component AppWindow inherits Window {
    callback add-url(string);
    title: "fast-down";
    preferred-height: 500px;
    in property <[DownloadData]> download-list: [
        {
            filename: "sdfsdf",
            speed: "100MB/s",
            percentage: "10MB / 100GB (10%)",
            remaining-time: "01:23:45",
            elapsed: "12:34:56",
            is-downloading: true,
            progress: [
                {
                    is-blank: false,
                    width: 0.2,
                },
                {
                    is-blank: true,
                    width: 0.6,
                },
                {
                    is-blank: false,
                    width: 0.2,
                },
            ]
        },
        {
            filename: "sdfsdf",
            speed: "100MB/s",
            percentage: "10MB / 100GB (10%)",
            remaining-time: "01:23:45",
            elapsed: "12:34:56",
            is-downloading: false,
            progress: [
                {
                    is-blank: false,
                    width: 0.2,
                },
                {
                    is-blank: true,
                    width: 0.6,
                },
                {
                    is-blank: false,
                    width: 0.2,
                },
            ]
        },
    ];

    TabWidget {
        Tab {
            title: @tr("Home");

            Home {
                width: 100%;
                height: 100%;
                download-list: download-list;
                add-url(url) => {
                    add-url(url)
                }
            }
        }

        Tab {
            title: @tr("Settings");
        }

        Tab {
            title: @tr("About");

            VerticalBox {
                Text {
                    text: @tr("About Page");
                }
            }
        }
    }
}
