import { HorizontalBox, VerticalBox, StandardTableView, GroupBox, StyleMetrics, LineEdit, Button, ListView, TextEdit, ProgressIndicator } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "fast-down";
    preferred-height: 500px;

    VerticalLayout {
        spacing: StyleMetrics.layout-spacing;
        ListView {
            for i in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]: VerticalBox {
                Text {
                    text: "File Name";
                }

                HorizontalLayout {
                    VerticalBox {
                        Text {
                            text: @tr("Speed");
                        }

                        Text {
                            text: "10 MB/s";
                        }
                    }

                    VerticalBox {
                        Text {
                            text: @tr("Progress");
                        }

                        Text {
                            text: "10 MB / 5 GB";
                        }
                    }

                    VerticalBox {
                        Text {
                            text: @tr("Remaining Time");
                        }

                        Text {
                            text: "01:23:45";
                        }
                    }
                }

                ProgressIndicator {
                    progress: 0.1;
                }
            }
        }

        HorizontalLayout {
            padding: 8px;
            spacing: StyleMetrics.layout-spacing;
            // TextEdit {
            //     height: 43px;
            //     placeholder-text: @tr("URL");
            //     wrap: TextWrap.no-wrap;
            // }
            LineEdit {
                placeholder-text: @tr("URL");
            }

            Button {
                text: @tr("Add");
            }

            Button {
                text: @tr("Settings");
            }
        }
    }
}
