import { HorizontalBox, StyleMetrics, LineEdit, Button, ListView } from "std-widgets.slint";
import { DownloadData, DownloadItem } from "download-item.slint";

export component Home {
    callback add-url(string);
    callback stop(int);
    callback resume(int);
    callback delete(int);
    callback open(int);
    callback open-folder(int);
    in property <[DownloadData]> download-list;
    VerticalLayout {
        spacing: StyleMetrics.layout-spacing;
        HorizontalBox {
            text-edit := LineEdit {
                placeholder-text: @tr("URL");
                accepted(text) => {
                    add-url(text);
                    self.text = "";
                }
            }

            Button {
                text: @tr("Add");
                clicked => {
                    add-url(text-edit.text);
                    text-edit.text = "";
                }
            }
        }

        ListView {
            horizontal-scrollbar-policy: ScrollBarPolicy.always-off;
            for d[i] in download-list: DownloadItem {
                file-name: d.file-name;
                percentage: d.percentage;
                remaining-time: d.remaining-time;
                speed: d.speed;
                elapsed: d.elapsed;
                is-downloading: d.is-downloading;
                progress: d.progress;
                stop => {
                    stop(i)
                }
                resume => {
                    resume(i)
                }
                delete => {
                    delete(i)
                }
                open => {
                    open(i)
                }
                open-folder => {
                    open-folder(i)
                }
            }
        }
    }
}
