import { HorizontalBox, StyleMetrics, LineEdit, Button, ListView } from "std-widgets.slint";
import { DownloadData, DownloadItem } from "download-item.slint";

export component Home {
    callback add-url(string);
    in property <[DownloadData]> download-list;

    VerticalLayout {
        spacing: StyleMetrics.layout-spacing;

        HorizontalBox {
            text-edit := LineEdit {
                placeholder-text: @tr("URL");
                accepted(text) => {
                    add-url(text);
                    self.text = "";
                }
            }

            Button {
                text: @tr("Add");
                clicked => {
                    add-url(text-edit.text);
                    text-edit.text = "";
                }
            }
        }

        ListView {
            for d in download-list: DownloadItem {
                filename: d.filename;
                percentage: d.percentage;
                remaining-time: d.remaining-time;
                speed: d.speed;
                elapsed: d.elapsed;
                is-downloading: d.is-downloading;
                progress: d.progress;
            }
        }
    }
}
