mod display_progress;
pub mod download;
mod download_multi_threads;
pub mod download_progress;
mod download_single_thread;
pub mod format_file_size;
mod get_chunks;
pub mod get_url_info;
pub mod merge_progress;
mod progresses_remain;
pub mod progresses_size;
